[build]
  command = "nvm install 14 && nvm use 14 && npm install && nvm install 18 && nvm use 18 && npm run build"
  publish = "dist/contacts"
  environment = { NODE_VERSION = "18" } 
  functions = "netlify/functions"

[context.production]
  command = "npm run build --prod"
